baseURL = "https://rdner.de/"
languageCode = "en-us"
title = "rdner's blog"
theme = "dark-pragma"
relativeURLs = true
sectionPagesMenu = "main"
enableRobotsTXT = true
pygmentsCodefences = true
copyright = 'Unless indicated otherwise, the content is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/" rel="nofollow noreferrer" target="_blank">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)</a>.<br><a xmlns:cc="http://creativecommons.org/ns#" href="https://rdner.de/about" property="cc:attributionName" rel="cc:attributionURL">Denis Rechkunov</a>&nbsp;(<a href="mailto:denis@rdner.de">denis@rdner.de</a>)'

[markup]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
tabWidth = 2

[markup.tableOfContents]
endLevel = 3
startLevel = 1

[params]
UserPicture = "https://www.gravatar.com/avatar/0f18ade06d929797f7c7e418c509a0b1?s=512"
AuthorName = "Denis Rechkunov"
Description = "Personal stories and thoughts"
LinkedIn = "rdner"
Github = "rdner"
Mastodon = "mastodon.social/@rdner"
Email = "denis@rdner.de"
CustomHead = "<script defer data-domain=\"rdner.de\" src=\"https://plausible.io/js/script.js\"></script>"

[privacy]
  [privacy.vimeo]
    enableDNT = true

[menu]
	[[menu.main]]
		identifier = "posts"
		name = "Posts"
		title = "My blog posts"
		url = "/posts/"
		weight = -120
	[[menu.main]]
		identifier = "music"
		name = "Music"
		title = "My original music"
		url = "/music/"
		weight = -110
	[[menu.main]]
		identifier = "talks"
		name = "Talks"
		title = "My talks"
		url = "/talks/"
		weight = -100
	[[menu.main]]
		identifier = "cv"
		name = "CV"
		title = "My most recent CV"
		url = "/cv.html"
		weight = -90
