baseURL: https://rdner.de/
languageCode: en-US
title: rdner's blog
theme: loud-pragmatic
enableRobotsTXT: true
copyright: Denis Rechkunov
markup:
  goldmark:
    parser:
      attribute: true
  highlight:
    tabWidth: 2
    style: vulcan
  tableOfContents:
    endLevel: 3
    startLevel: 1
params:
  licenseURL: http://creativecommons.org/licenses/by-nc-sa/4.0/
  author:
    pictureURL: /images/rdner.jpg
    name: Denis Rechkunov
    email: denis@rdner.de
  contact:
    email: denis@rdner.de
  customHTML:
    head: '<meta name="fediverse:creator" content="@rdner@mastodon.social"><script defer data-domain="rdner.de" src="https://plausible.io/js/script.js"></script>'
    footer: ' is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;">.<script type="text/javascript">w=document.getElementById("whoami");if(w){w.onclick=()=>eval(atob("ZG9jdW1lbnQubG9jYXRpb24gPSAiL3ZpZGVvcy8xLm1wNCI="))}</script>'

  theme:
    colors:
      main: "#5a2673"
      background: "#141116"
      highlight: "#8952A2"
      border: "#D7DADC"
      card:
        background: "#252426"
        overlay: "rgba(20,17,22,0.6)"
      text:
        main: "#D7DADC"
        secondary: "#C0C0C0"
        highlight: "#FFF"

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  vimeo:
    enableDNT: true
  x:
    disable: true
  youTube:
    privacyEnhanced: true
menu:
  main:
    - identifier: talks
      name: Talks
      title: My talks
      url: /talks/
      weight: 20
    - identifier: cv
      name: CV
      title: My most recent CV
      url: /cv.html
      weight: 21
    - identifier: linkedin
      name: LinkedIn
      title: My LinkedIn profile
      url: https://www.linkedin.com/in/rdner
      weight: 22
    - identifier: github
      name: Github
      title: My Github profile
      url: https://github.com/rdner
      weight: 23
    - identifier: mastodon
      name: Mastodon
      title: My Mastodon profile
      url: https://mastodon.social/@rdner
      weight: 24
      params:
        rel: me
