baseURL = "https://rdner.de/"
languageCode = "en-US"
title = "rdner's blog"
theme = "darker-pragma"
sectionPagesMenu = "main"
enableRobotsTXT = true
pygmentsCodefences = true
copyright = 'Denis Rechkunov'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
			attribute = true
	[markup.highlight]
		tabWidth = 2
	  style = 'vulcan'
	[markup.tableOfContents]
		endLevel = 3
		startLevel = 1

[params]
	licenseURL = "http://creativecommons.org/licenses/by-nc-sa/4.0/"
	userPictureURL = "/images/rdner.jpg"
	authorName = "Denis Rechkunov"
	[params.contact]
		email = "denis@rdner.de"
	[params.customHTML]
		# head = '<meta name="fediverse:creator" content="@rdner@mastodon.social"><script defer data-domain=\"rdner.de\" src=\"https://plausible.io/js/script.js\"></script>'
		footer = 'Unless indicated otherwise, the content is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/" rel="nofollow noreferrer" target="_blank">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)</a>.<a style="display:none;" rel="me" href="https://mastodon.social/@rdner"></a><script type="text/javascript">w=document.getElementById("whoami");if(w){w.onclick=()=>eval(atob("ZG9jdW1lbnQubG9jYXRpb249J2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZFF3NHc5V2dYY1En"))}</script>'

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    disable = true
  [privacy.youTube]
    privacyEnhanced = true

[menu]
	[[menu.main]]
		identifier = "posts"
		name = "Posts"
		title = "My blog posts"
		url = "/posts/"
		weight = -120
	[[menu.main]]
		identifier = "music"
		name = "Music"
		title = "My original music"
		url = "/music/"
		weight = -110
	[[menu.main]]
		identifier = "talks"
		name = "Talks"
		title = "My talks"
		url = "/talks/"
		weight = -100
	[[menu.main]]
		identifier = "cv"
		name = "CV"
		title = "My most recent CV"
		url = "/cv.html"
		weight = -90
	[[menu.main]]
		identifier = "linkedin"
		name = "LinkedIn"
		title = "My LinkedIn profile"
		url = "https://www.linkedin.com/in/rdner"
		weight = -80
	[[menu.main]]
		identifier = "github"
		name = "Github"
		title = "My Github profile"
		url = "https://github.com/rdner"
		weight = -70
	[[menu.main]]
		identifier = "mastodon"
		name = "Mastodon"
		title = "My Mastodon profile"
		url = "https://mastodon.social/@rdner"
		weight = -60
